theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

encoding: "utf-8"
# settings from web
# Site settings
title: Nyanya Notes    				  	#你博客的标题
SEOTitle: Nyanya Notes    	 #显示在浏览器上搜索的时候显示的标题
header-img: "/img/banner.png"  	#显示在首页的背景图片
email: spinning_eggs@163.com	
description: "Nya nya nya"  			 #网站介绍
keyword: "Nya, Blog, 博客, Note, note" #关键词
url: "https://misaki-nyanya.github.io/notes/"          # 这个就是填写你的博客地址
baseurl: "notes"      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "说点装逼的话。。。"
sidebar-avatar: "/img/avatar.png"      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
